package frc.robot.wrist;

public enum WristState {
  IDLE,
  UNJAM,
  PRE_MATCH_HOMING,

  CORAL_SCORE_LV1,
  CORAL_SCORE_LV2,
  CORAL_SCORE_LV3,
  CORAL_SCORE_LV4,

  ALGAE_FORWARD_NET,
  ALGAE_BACKWARD_NET,
  ALGAE_PROCESSOR,

  SOURCE_INTAKE,
  GROUND_CORAL_INTAKE,
  GROUND_ALGAE_INTAKE;
}
